version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
      timeout: 30
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/deploy_app.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root
