version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /home/ec2-user/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_java_tomcat.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
      runas: ec2-user
